### ISSUE TITLE
[Anti-adblock] tvserial.it

### ISSUE THREAD

**Issue by jackpallet** [NanoAdblocker/NanoFilters#275]
URLs where this issue occurs (Required)
http://www.tvserial.it/

 Screenshots (Required)
![tvserial1](https://user-images.githubusercontent.com/46008931/53247505-da3d3100-36b3-11e9-978d-b8d861b63b3f.jpg)

Screenshot of console (Required, press `F12` to open the console)
![tvserial2](https://user-images.githubusercontent.com/46008931/53247557-f93bc300-36b3-11e9-8b36-e7d1e26f08a7.jpg)
![tvserial3](https://user-images.githubusercontent.com/46008931/53247587-05278500-36b4-11e9-9d97-4e8292c251c9.jpg)
![tvserial4](https://user-images.githubusercontent.com/46008931/53247589-08227580-36b4-11e9-98ff-3afe9e894255.jpg)
![tvserial5](https://user-images.githubusercontent.com/46008931/53247596-0a84cf80-36b4-11e9-9654-c282e1c3cac2.jpg)

Anything else you believe to be useful

Also after disabled Ublockorigin, deleted cookies and cache the problem is still here

- Operating System and Version: Windows 7 64 bit
- Browser and Version: Waterfox 56.2.7.1 (64 bit)
- Nano Adblocker Version: uBlock Origin 1.18.4
- Nano Defender Version: 15.0.0.95

Your filter lists:

Integrati (5/7)

    uBlock filters​

​​​​13.705 usati su 13.765​​
​​
uBlock filters – Badware risks​
​​​​63 usati su 63​​
​​
uBlock filters – Privacy​​​​​152 usati su 158​​
​​
uBlock filters – Resource abuse​​​​​136 usati su 282​​
​​
uBlock filters – Unbreak​​​​​790 usati su 820​​

    ​​ 

Pubblicità (2/4)

    Adblock Warning Removal List​

​​​​609 usati su 615​​
​​
EasyList​
​​​​87.643 usati su 87.773​​

    ​​ 

Privacy (1/3)

    EasyPrivacy​

​​​​16.547 usati su 16.597​​

    ​​ 

Domini con Malware (2/4)

    Malware Domain List​​​​​1.094 usati su 1.109​​

​​
Malware domains​
​​​​26.913 usati su 26.913​​

    ​​ 

Elementi fastidiosi (0/6)

Multiuso (1/4)

    Peter Lowe’s Ad and tracking server list​

​​​​2.964 usati su 2.965​​

    ​​ 

Regioni, lingue (1/37)

    ITA: EasyList Italy​

​​​​4.772 usati su 4.772​​

    ​​ 

Personalizzate (3/3)

    Nano Defender Integration​​

​​​2.556 usati su 2.671​​
​​
Nano Filters​​
​​​179 usati su 183​​
​​
Nano Filters - Whitelist​​
​​​1 usati su 1​​​​

**Comment by mapx-** [comment]
already fixed in ublock filters, it seems your lists are not updated

**Comment by jackpallet** [comment]
Ublock filters and Nanofilters are updated, but the problem is still there

**Comment by jspenguin2017** [comment]
Can't reproduce, it works fine for me. 
![image](https://user-images.githubusercontent.com/7283682/53535504-48249680-3ac0-11e9-94a2-f5c9e0d88490.png)
