### ISSUE TITLE
[Popup] vidstream.top

### ISSUE THREAD

**Issue by mimo2004moh** [NanoAdblocker/NanoFilters#377]
### URLs where this issue occurs (Required)
https://vidstream.top

### Screenshots (Required)
this when nano disable
![Capture](https://user-images.githubusercontent.com/53051408/61595522-9b76bd00-abf8-11e9-9a7b-78a015626e34.PNG)
this when enable
![Capture2](https://user-images.githubusercontent.com/53051408/61595524-a5002500-abf8-11e9-8335-a4f8bcbea85f.PNG)

### Screenshot of console (Required, press `F12` to open the console)
![Capture3](https://user-images.githubusercontent.com/53051408/61595528-ab8e9c80-abf8-11e9-906d-398528d76783.PNG)

### Describe the issue (Optional if obvious)
when the popups not open <blocked by nano> the anti-adblock appear

#### Environment (Required)

Operating System and Version: windows 10 x64
Browser and Version: firefox 68.0.1
Nano Adblocker Version: 1.0.0.120
Nano Defender Version (Optional if you are not using it): 15.0.0154

**Comment by mimo2004moh** [comment]
![Capture4](https://user-images.githubusercontent.com/53051408/61595551-edb7de00-abf8-11e9-9ff5-90064006bc5e.PNG)

**Comment by llacb47** [comment]
You have to click on console after hitting F12 to view the console.

**Comment by jspenguin2017** [comment]
@okiehsch There's a popup. 

Can't reproduce anti-adblock.

**Comment by okiehsch** [comment]
Fixed.

**Comment by mimo2004moh** [comment]
@okiehsch  @jspenguin2017  the anti adblock still not fix
check the link https://vidstream.top/v/HQBSdyQA0M/?vclid=f96d5c5ebc194c21277fabe173d03ddd4caf121e581b83791b46f385DbbbBPGxbBbIbBoFvWRYoXGAbBIBbBTPdbBbIbBAAAbrovprovRYpBvWYBIBbBlpoOBbIbBXjZepoFIuZtobFIoHyOqFbbBbw

**Comment by okiehsch** [comment]
> check the link `https://vidstream.top/v/HQBSdyQA0M/?vclid=f96d5c5ebc194c21277fabe173d03ddd4caf121e581b83791b46f385DbbbBPGxbBbIbBoFvWRYoXGAbBIBbBTPdbBbIbBAAAbrovprovRYpBvWYBIBbBlpoOBbIbBXjZepoFIuZtobFIoHyOqFbbBbw`

![image](https://user-images.githubusercontent.com/16838044/61602067-799d2a80-ac38-11e9-9846-9ddf1330b5da.png)

**Comment by llacb47** [comment]
There's probably a session token or something. A little harder to debug.

**Comment by mimo2004moh** [comment]
@okiehsch ok go to: https://www.egy.best/movie/wine-country-2019/?ref=home-new
and click the yellow buttom
![Capture](https://user-images.githubusercontent.com/53051408/61602740-18c32180-ac3b-11e9-8b89-2a49c0bd5d50.PNG)

**Comment by okiehsch** [comment]
Do I need to be logged in?
![image](https://user-images.githubusercontent.com/16838044/61602929-d9e19b80-ac3b-11e9-8ad4-d81e50d1335a.png)

**Comment by mimo2004moh** [comment]
no  you need vpn

**Comment by okiehsch** [comment]
What country?

**Comment by mimo2004moh** [comment]
use arabic and turkey also work

**Comment by okiehsch** [comment]
![image](https://user-images.githubusercontent.com/16838044/61603131-b9661100-ac3c-11e9-8ad3-590f510488cd.png)

**Comment by mimo2004moh** [comment]
yes try to play the movie

**Comment by mimo2004moh** [comment]
the anti-adblock appear 
and when disable nano adblocker and play the movie popups open and the player work fine

**Comment by okiehsch** [comment]
I can reproduce but the video will not play on my end even with uBO disabled.
Does 
`vidstream.top##+js(setTimeout-defuser.js, reject)`
work for you?

**Comment by mimo2004moh** [comment]
no

**Comment by okiehsch** [comment]
I always get the "No compatible source was found" message.
I can't reproduce the anti adblock message if I add
`vidstream.top##+js(setTimeout-defuser.js, '0x)`

**Comment by mimo2004moh** [comment]
just click on it many time its work

**Comment by mimo2004moh** [comment]
It seems that they are checking if popup was opened.

**Comment by okiehsch** [comment]
So  adding
`````
vidstream.top#@#+js(window.open-defuser.js)
@@||deloplen.com/afu.php$popup,domain=vidstream.top
````
to your filter list works for you?
That will allow the popup but block the the resulting page.

**Comment by mimo2004moh** [comment]
still not work and anti-adblock appear

**Comment by okiehsch** [comment]
I give up. ;)

**Comment by mimo2004moh** [comment]
yah its hard

**Comment by okiehsch** [comment]
I know that the site checks for the popup that was the whole point of yesterdays filter
`vidstream.top##+js(setTimeout-defuser.js, '0x)`
that will break the whole popup script and as a result there will be no popup.

````
vidstream.top#@#+js(window.open-defuser.js)
@@||deloplen.com/afu.php$popup,domain=vidstream.top
````
allows the popup, so I don't understand why it still does not work on your end.
@jspenguin2017 can you try?

**Comment by jspenguin2017** [comment]
I haven't tried to reproduce this, I'll take a look later.

**Comment by jspenguin2017** [comment]
@okiehsch None of your rules work. Looking at AdGuard's solution, we'll probably need a new script snippet or two.

**Comment by YASINEDr** [comment]
still can not download from this important website  !!!!

![screenshot-vidstream to-2019 10 04-01_59_37](https://user-images.githubusercontent.com/34688076/66173983-e6766d00-e64a-11e9-8332-7c8fc5970b82.jpg)

**Comment by mapx-** [comment]
use adguard adblocker

**Comment by hmz777** [comment]
vidstream launches a popup to check for ad blockers, if it got blocked they show you that annoying screen, so what I do is I pause ublock origin (with nano defender), do an "empty cache and hard reload" from the dev tools, the popup will open but ublock origin will intercept it from actually loading and the stream will load correctly then you can re-enable your ad blocker and reload the stream, again it will open correctly and you can watch without interruption.
