### ISSUE TITLE
[Anti-adblock] freetutorialseu.com

### ISSUE THREAD

**Issue by Signup-pawan** [NanoAdblocker/NanoFilters#402]
### URLs where this issue occurs (Required)

https://www.freetutorialseu.com/
### Screenshots (Required)
![image](https://user-images.githubusercontent.com/55138565/65341481-1c006c80-dbee-11e9-9b47-199f562283ca.png)

### Screenshot of console (Required, press `F12` to open the console)

![image](https://user-images.githubusercontent.com/55138565/65341314-b318f480-dbed-11e9-983a-b25577c49392.png)

### Describe the issue (Optional if obvious)
Asking to Disable the Adblock

### Anything else you believe to be useful (Optional)
How to add the websites to the list when we get these type of popups? Noticed few sites still asking to disable the Adblock

#### Environment (Required)

- Operating System and Version: Windows 10 x64
- Browser and Version: Chrome 76.0.3809.132
- Nano Adblocker Version: 1.0.0.126
- Nano Defender Version (Optional if you are not using it): 15.0.0.168

#### Your filter lists (Required)

![image](https://user-images.githubusercontent.com/55138565/65341791-cc6e7080-dbee-11e9-9f45-e0e0a897d7d6.png)

**Comment by mapx-** [comment]
fixed

**Comment by Signup-pawan** [comment]
> fixed

HI, Still getting warning to disable ad-block. I also wanted to can we add the website from our end to the list that can able to disable this warnings?

**Comment by mapx-** [comment]
- Update all your lists (purge + update now)
- adblock warning removal list is a useless one (invented by ABP for very very light anti adb warnings)

**Comment by jspenguin2017** [comment]
Fix working for me. Closing.

**Comment by Signup-pawan** [comment]
Thanks, Its Working for me now. Every time I need to create a new issue for Every website? or there any workaround for adding the website to the list? please let me know.

**Comment by Signup-pawan** [comment]
> fixed

Hi, Its Working now. Thanks.

**Comment by jspenguin2017** [comment]
You can use Quick Issue Reporter, that should be much easier than creating new issues. If you know how to create custom filters rules, you're certainly free to do that as well.
