### ISSUE TITLE
[Anti-adblock] port.hu

### ISSUE THREAD

**Issue by bandi88** [NanoAdblocker/NanoFilters#469]
### URLs where this issue occurs (Required)
https://port.hu/esemeny/egyeb/spirit-szinhaz-cabaret-2-resz-online/event-5733576

### Screenshots (Required)
![image](https://user-images.githubusercontent.com/23141180/77796199-2143e580-706f-11ea-9fe8-dfb6dbc392ba.png)

### Screenshot of console (Required, press `F12` to open the console)
![image](https://user-images.githubusercontent.com/23141180/77796307-518b8400-706f-11ea-9cb6-90791f312671.png)

### Describe the issue (Optional if obvious)
Unable to read any articles of the website port.hu, if my uBlock Origin with Nano Defender is active. I get a message, that the website detected my ad-blockers. And it does not let me to proceed if I don't disable them.

### Reproduction Steps (Optional if trivial)
Just simply load the website, link above.

#### Environment (Required)
- OS: Linux with kernel 4.19.0-8-amd64
- Browser: Google Chrome v. 80.0.3987.149 64bit
- Nano Adblocker Version: I don't use it. Used uBlock Origin v. 1.24.4 instead
- Nano Defender Version: 15.0.0.196

#### Your filter lists (Required)
![image](https://user-images.githubusercontent.com/23141180/77796724-1d649300-7070-11ea-8f05-bb06776b7415.png)

#### Your custom filters (Required if you have any)
port.hu##.as-oil-content-overlay

#### Your other extensions (Required if you have any)
Google Opt-Out

**Comment by mapx-** [comment]
fixed today
https://github.com/NanoMeow/QuickReports/issues/3412

update uBO filters list

**Comment by bandi88** [comment]
After refreshing the uBO filter lists, restarting my browser and computer, the problem still persists. Please let us know, when this should be fixed.

**Comment by mapx-** [comment]
> After refreshing the uBO filter lists

Did you `purge all caches` + update ?
Did you disable all other blocking extensions in your browser ?

**Comment by bandi88** [comment]
> > After refreshing the uBO filter lists
> 
> Did you `purge all caches` + update ?
> Did you disable all other blocking extensions in your browser ?

Yes, I did purge at first. And then the update. Also blocking other extensions has not provided any further help.

**Comment by mapx-** [comment]
open the logger, refresh the page, select only the blocked items, post here the screenshot

**Comment by bandi88** [comment]
The screenshot:
![image](https://user-images.githubusercontent.com/23141180/77820460-cb108a00-70e2-11ea-86f2-f2d3b341d06c.png)

**Comment by mapx-** [comment]
uBO logger, not the console

**Comment by bandi88** [comment]
That is interesting. Now, it seems to be working. Any idea, why suddenly, after 1 hour it is working?

**Comment by mapx-** [comment]
It's all on your side :)

**Comment by mapx-** [comment]
Sometimes the updating process just fails (browser, provider, network issues)
